[package]
name = "bevy_multicam"
version = "0.1.0"
authors = ["Black Phlox <bphlox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
bevy = "0.5"
bevy_flycam = { path = "./lib/bevy_flycam" }

[dev-dependencies]
ron = "*"
serde = { version = "1.0.60", features = ["serde_derive"] }