[package]
name = "bevy_config_cam"
version = "0.1.0"
authors = ["Black Phlox <bphlox@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/BlackPhlox/bevy_config_cam"
documentation = "https://docs.rs/bevy_config_cam"
description = "A Swiss Army knife of a camera plugin that allows for easy setup and configuration of a wide variety of types of moveable camera for a scene."
keywords = ["gamedev", "bevy", "camera", "fps", "3d", ]
categories = ["game-development", "game-engines", ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "bevy_config_cam"

[dependencies]
rand = "0.8.0"
bevy = { version = "0.5", default-features = false, features = ["render"] }
bevy_flycam = { path = "./lib/bevy_flycam" }

[dev-dependencies]
bevy = { version = "0.5", default-features = false, features = ["render", "bevy_winit", "bevy_wgpu", "bevy_gltf"] }
ron = "*"
serde = { version = "1.0.60", features = ["serde_derive"] }

[target.'cfg(target_os = "linux")'.dev-dependencies]
bevy = { version = "0.5", default-features = false, features = [ "x11", "wayland" ] }